# modules/config.py

# =========================================================================
# DE-PARA DE ORGANIZAÇÕES (DOMÍNIO DO NEGÓCIO)
# =========================================================================
MAPPING_ALUCOM = {1327, 1329, 1353, 1363, 1365, 1367, 1370, 1373, 1376, 1377}
MAPPING_IP = {1346, 1349, 1350, 1364, 1368, 1371}
MAPPING_MOREIA = {1313, 1326, 1328, 1358, 1369}
MAPPING_AS = {1378}

# =========================================================================
# REGRAS DE EXCEÇÃO E FILTROS
# =========================================================================
ORGANIZACOES_BLOQUEADAS = {1123, 1366}
CLIENTES_BLOQUEADOS = {2131, 2707}
FALSOS_RESERVAS = {10487}

# ===========================================================================
# CONSTATANTES DE CLIENTES
#============================================================================
DEPARA_EXCECOES = {
        10824: 10711,
        4182: 4174,
        10450: 3915,
        10427: 10414,
        10853: 10806,
        10434: 3634,
        3362: 3332,
        4439: 2879,
        4467: 4465,
        4464: 4466,
        11920: 11919,
        10935: 10823,
}
MAPA_SAO_LUIS = {
        # === IPAM (Secretaria 1194) ===
        11791: (1194, "INSTITUTO DE PREVIDÊNCIA E ASSISTÊNCIA DO MUNICÍPIO - IPAM"),
        4467:  (1194, "INSTITUTO DE PREVIDÊNCIA E ASSISTÊNCIA DO MUNICÍPIO - IPAM"),
        4465:  (1194, "INSTITUTO DE PREVIDÊNCIA E ASSISTÊNCIA DO MUNICÍPIO - IPAM"),
        11932: (1194, "INSTITUTO DE PREVIDÊNCIA E ASSISTÊNCIA DO MUNICÍPIO - IPAM"),
        11933: (1194, "INSTITUTO DE PREVIDÊNCIA E ASSISTÊNCIA DO MUNICÍPIO - IPAM"),
        
        # === SEMUSC (Secretaria 1197) ===
        4464:  (1197, "SECRETARIA MUNICIPAL DE SEGURANÇA COM CIDADANIA - SEMUSC"),
        4466:  (1197, "SECRETARIA MUNICIPAL DE SEGURANÇA COM CIDADANIA - SEMUSC"),
        10502: (1197, "SECRETARIA MUNICIPAL DE SEGURANÇA COM CIDADANIA - SEMUSC"),
        10513: (1197, "SECRETARIA MUNICIPAL DE SEGURANÇA COM CIDADANIA - SEMUSC"),
        11924: (1197, "SECRETARIA MUNICIPAL DE SEGURANÇA COM CIDADANIA - SEMUSC"),
        
        # === SMTT (Secretaria 1303) ===
        10714: (1303, "SECRETARIA DE TRÂNSITO E TRANSPORTES - SMTT"),
        10591: (1303, "SECRETARIA DE TRÂNSITO E TRANSPORTES - SMTT"),
        11928: (1303, "SECRETARIA DE TRÂNSITO E TRANSPORTES - SMTT"),
        
        # === SEMFAZ / PM SÃO LUIS (Secretaria 1220) ===
        10400: (1220, "SECRETARIA DA FAZENDA - SEMFAZ"),
        10401: (1220, "SECRETARIA DA FAZENDA - SEMFAZ"),
        11919: (1220, "SECRETARIA DA FAZENDA - SEMFAZ"),
        11920: (1220, "SECRETARIA DA FAZENDA - SEMFAZ"),
    }
SAO_LUIS_CONFIG = {
    "ID_PREF_ALVO": 287,
    "NOME_PREF_ALVO": "PREFEITURA MUNICIPAL DE SÃO LUÍS"
}
MAPA_REGIOS_PCPB = {
    "CAMPINA GRANDE": "CAMPINA GRANDE",
    "GUARABIRA": "GUARABIRA",
    "JOAO PESSOA": "JOÃO PESSOA",
    "CAPITAL": "JOÃO PESSOA",
    "MANGABEIRA": "JOÃO PESSOA",
    "PATOS": "PATOS",
    "SANTA RITA": "SANTA RITA",
    "ALHANDRA": "ALHANDRA",
    "CAAPORA": "CAAPORÃ",
    "MAMANGUAPE": "MAMANGUAPE",
    "CONDE": "CONDE",
    "PEDRAS DE FOGO": "PEDRAS DE FOGO",
    "PITIMBU": "PITIMBU",
    "PILAR": "PILAR",
    "PILOES": "PILÕES",
    "JERICO": "JERICÓ"
}
MAPA_IDS_SINTETICOS_PCPB = {
    "JOÃO PESSOA": 900001,
    "CAMPINA GRANDE": 900002,
    "GUARABIRA": 900003,
    "PATOS": 900004,
    "SANTA RITA": 900005,
    "ALHANDRA": 900006,
    "CAAPORÃ": 900007,
    "MAMANGUAPE": 900008,
    "CONDE": 900009,
    "PEDRAS DE FOGO": 900010,
    "PITIMBU": 900011,
    "PILAR": 900012,
    "PILÕES": 900013,
    "JERICÓ": 900014,
    "SEDE / OUTROS": 900015
}


# ===========================================================================
# CONSTATANTES DE CONTRATOS
#============================================================================
MAP_TIPO = {'LICITACAO': 1, 'PESSOA JURIDICA': 2, 'PESSOA FISICA': 3}
MAP_STATUS = {'AGUARDANDO INICIO': 1, 'EM ANDAMENTO': 2, 'ENCERRADO': 3}
MAP_EVENT_TYPES = {
    'CADASTRO': 1,
    'ADITIVO DE PRAZO': 2,
    'ADITIVO DE QUANTIDADE': 3,
    'ADITIVO DE REAJUSTE': 4,
    'ADITIVO DE SUPRESSAO': 5,
    'ADITIVO MODIFICAÇÃO DE ITEM': 6,
    'APOSTILAMENTO': 7
}
ABBREVIATIONS = {
    'ESPCEX': 'ESCOLA PREPARATÓRIA DE CADETES DO EXÉRCITO',
    'FUNASA': 'FUNDAÇÃO NACIONAL DE SAÚDE',
    '20º RCB': '20º REGIMENTO DE CAVALARIA BLINDADO - CAMPO GRANDE',
    '20 RCB': '20º REGIMENTO DE CAVALARIA BLINDADO - CAMPO GRANDE',
    'CRN1': 'CONSELHO REGIONAL DE NUTRIÇÃO 1ª REGIÃO (CRN-1)',
    'CLA': 'COMANDO DA AERONÁUTICA - CENTRO DE LANÇAMENTO DE ALCÂNTARA - BASE SÃO LUIS',
    'CREF': 'CONSELHO REGIONAL DE EDUCAÇÃO FISICA DA 3º REGIÃO - SC',
    'COREN DF': 'CONSELHO REGIONAL DE ENFERMAGEM DO DISTRITO FEDERAL',
    'CINDACTA I': 'MINISTÉRIO DA DEFESA - CINDACTA I - GRUPAMENTO DE APOIO - DF',
    'CISNORDESTE SC': 'CONSÓRCIO INTERFEDERATIVO DE SAÚDE DO NORDESTE DE SANTA CATARINA',
    'CISNORDESTE': 'CONSÓRCIO INTERFEDERATIVO DE SAÚDE DO NORDESTE DE SANTA CATARINA',
    'ALECE': 'ASSEMBLEIA LEGISLATIVA DO ESTADO DO CEARÁ',
    'CMFOR': 'COMANDO DA MARINHA EM FORTALEZA',
    'EAMCE': 'ESCOLA DE APRENDIZES-MARINHEIROS DO CEARÁ',
    'UFC': 'UNIVERSIDADE FEDERAL DO CEARÁ',
    'IFCE': 'INSTITUTO FEDERAL DE EDUCAÇÃO E TECNOLOGIA - IFCE',
    '10A REGIAO MILITAR': '10ª REGIÃO MILITAR',
    '10ª REGIAO MILITAR': '10ª REGIÃO MILITAR',
    'ANA KALINCA': 'ANA KALINCA',
    'COMERCIAL DE MEDICAMENTOS CAVALCANTE LTDA - FARMÁCIA PREMIUM': 'COMERCIAL DE MEDICAMENTOS CAVALCANTE LTDA - FARMÁCIA PREMIUM',
    'H F DA ROCHA COMERCIO SERVIÇOS': 'HF DA ROCHA COMÉRCIO E SERVIÇOS DE INFORMÁTICA',
    'SECRETARIA MUNICIPAL DE SEGURANÇA COM CIDADANIA−SEMUSC': 'PREFEITURA MUNICIPAL DE SAO LUIS',
    'MARANHÃO PARCEIRIAS - MAPA': 'MARANHÃO PARCERIAS S.A - SÃO LUÍS',
    'CONSELHO FEDERAL DE FARMÁCIA': 'CONSELHO FEDERAL DE FARMCIA - DF',
    'TRIBUNAL REGIONAL ELEITORAL O RIO DE JANEIRO': 'TRIBUNAL REGIONAL ELEITORAL DO RIO DE JANEIRO - TRE - RIO DE JANEIRO',
    'JOANA D ARC CLAUDIO BRASIL DOD': 'JOANA DARC CLAUDIO BRASIL DODO',
    'ACG CONSTRUÇÕES E CONSERVAÇÃO AMBIENTAL LTDA': 'ACG CONSTRUÇÕES E CONSERVAÇÃO AMBIENTAL LTDA',
    'GOVERNO MUNICIPAL DE URUOCA - FUNDO MUNICIPAL DE SAÚDE': 'SEC. MUNICIPAL DA SAÚDE - URUOCA',
    'GOVERNO MUNICIPAL DE URUOCA - FUNDO MUNICIPAL DE EDUCAÇÃO': 'SEC. MUNICIPAL DA EDUCAÇÃO - FUNDEB - URUOCA',
    'ESCRITORIO DE REPRESENTAÇÃO DO MINISTÉRIO DAS RELAÇÕES EXTERIORES': 'MINISTÉRIO DE RELAÇÕES EXTERIORES - SP'
}